name: Workflow 1
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: |
          npm run lint
          echo "Linting Done"
      
      - name: Test
        run: |
          npm run test
          echo "Testing Done"

      - name: Github variables
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_ENV: $GITHUB_ENV"
          echo "GITHUB_PATH: $GITHUB_PATH"
          pwd
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
      
      - name: Deploying
        run: |
          echo "Deploy Done"
