name: Workflow 1
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: |
          npm run lint
          echo "Linting Done"
      
      - name: Test
        run: |
          npm run test
          echo "Testing Done"

      - name: Github variables
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
          echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
          echo "GITHUB_JOB: $GITHUB_JOB"
          echo "GITHUB_ACTION: $GITHUB_ACTION"
          echo "GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH"
          echo "GITHUB_ACTION_REF: $GITHUB_ACTION_REF"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          echo "GITHUB_API_URL: $GITHUB_API_URL"
          echo "GITHUB_SERVER_URL: $GITHUB_SERVER_URL"
          echo "GITHUB_GRAPHQL_URL: $GITHUB_GRAPHQL_URL"

      - name: Deploying
        run: |
          echo "Deploy Done"
